# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Barum Park
email: bp1094@nyu.edu
description: > # this means to ignore newlines until "url:"
    Personal webpage of Barum Park, PhD Candidate at the department of sociology, New York University
    295 Lafayette Street, New York, NY 10012
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url: https://baruuum.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: baruuum # your GitHub user name
twitter_username: # your Twitter handle
linkedin_username: # your LinkedIn user name
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
contact_note: 
google_analytics: UA-130591619-1

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: 
blog_description: This blog is a result of a time-consuming habit of mine to write down notes on quantitative methods that I find difficult to understand (which includes quite everything). Equations that appear in the posts are often unnecessarily lengthy. This is intentional, since what is deemed to be "clear," "obvious," and "easily shown" by statisticians or mathematicians is often not at all easy to grasp for sociologists like myself. I hope that these materials will be helpful for students who are as confused by these topics as I am/was when writing these notes. 

# Pagination
paginate: 10
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: baruuum 

# Optional features
show_social_icons:  false
enable_anchorjs:    false
#enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
    
news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
# kramdown:
    # math_engine: katex
    # input: GFM
    # syntax_highlighter: rouge
# highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]
keep_files: [images]
#exclude: [vendor, node_modules]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    # - jemoji
    # - jekyll-katex
    # - jekyll/scholar

# katex:
    # js_path : "/assets/js/"
    # rendering_options:
        # displayMode: false
        # maxSize: 1000
        
# Jekyll-Scholar
# scholar:

  # last_name: Park

  # style: apa
  # locale: en

  # sort_by: year
  # order: descending

  # source: /_bibliography/
  # bibliography: papers.bib
  # bibliography_template: bib

  # replace_strings: true
  # join_strings: true

  # details_dir: bibliography
  # details_layout: bibtex.html
  # details_link: Details

  # query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------

jquery_version: "1.12.4"
katex_version: "0.10.0"
anchorjs_version: "3.2.2"
